### ISSUE TITLE
univers.map not found (Ubuntu 16.04)

### ISSUE THREAD

**Issue by nise** [tud-cd/tudscr#29]
When I run the install script I get the following Error:

> updmap [ERROR]: The following map file(s) couldn't be found:
> updmap [ERROR]: 	univers.map (in /root/.texmf-config/web2c/updmap.cfg)
> updmap [ERROR]: Did you run mktexlsr?

I tried to follow [this](https://tex.stackexchange.com/questions/88423/manual-font-installation) instructions (like running `mktexlsr` and repeat the `sudo updmap-sys --enable Map=univers.map`), but could not find the location of the Univers files within texmf.

Have you any idea?

**Comment by keinstein** [comment]
First question: Are you installing the fonts system wide or just for your user account?
In the first case updmap-sys should ignore everything below /root. In the latter case you should try updmap-user without sudo instead.

Which install script are you using? The one from https://github.com/tud-cd/tudscr/releases/tag/fonts or https://github.com/tud-cd/tudscr/releases/tag/oldfonts ?. 

Otherwise: Which instructions are you following?

**Comment by nise** [comment]
I tried both scripts actually. 

After some trial and error I ended up by copied the tud.map section from the file `/var/lib/texmf/font/mp/pdflatex/updmap` into a file `tud.map` inside my local project folder. The file content looked something like:

> aubr8r UniversCE-Black <[8r.enc <aubr8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aubro8r UniversCE-BlackOblique <[8r.enc <aubro8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aunb8r UniversCE-Bold <[8r.enc <aunb8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aunbo8r UniversCE-BoldOblique <[8r.enc <aunbo8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aunl8r UniversCE-Light <[8r.enc <aunl8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aunlo8r UniversCE-LightOblique <[8r.enc <aunlo8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aunr8r UniversCE-Medium <[8r.enc <aunr8a.pfb " TeXBase1Encoding ReEncodeFont " 
> aunro8r UniversCE-Oblique <[8r.enc <aunro8a.pfb " TeXBase1Encoding ReEncodeFont " 
> dinb8r DIN-Bold <[8r.enc <dinb8a.pfb " TeXBase1Encoding ReEncodeFont " 
> dinbo8r DIN-Bold <[8r.enc <dinb8a.pfb " TeXBase1Encoding ReEncodeFont 0.167 SlantFont " 


In my latex class (or in the *.tex file) I used the following code in order to render different Univers and DIN Bold Fonts:

```
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc} 

\RequirePackage[english,ngerman]{babel}
\iflnienglish\selectlanguage{english}\def\bbl@main@language{english}\fi
\DeclareFixedFont{\univLightIX}{T1}{aun}{l}{n}{9}
\DeclareFixedFont{\univBoldIX}{T1}{aun}{b}{n}{9}
\DeclareFixedFont{\univLightXI}{T1}{aun}{l}{n}{11}
\DeclareFixedFont{\univLightObliqueXI}{T1}{aun}{l}{sl}{11}
\DeclareFixedFont{\univBoldXI}{T1}{aun}{b}{n}{11}
\DeclareFixedFont{\univLightVII}{T1}{aun}{l}{n}{7}
\DeclareFixedFont{\univLightObliqueVII}{T1}{aun}{l}{sl}{7}

\pdfmapfile{=tud.map}
```

**Comment by keinstein** [comment]
Since February 2018 the new TUD CD font is Open Sans.

If you maintain a LaTeX class I'd suggest to put it here on GitHub or base it on something similar.

> Then I copyed the tudscr.map section from the file /var/lib/texmf/font/mp/pdflatex/updmap into a file tud.map inside my local project folder. The file content looked something like:

tud.map and tudscr.map are linked to different font sets. 

> aubr8r UniversCE-Black <[8r.enc <aubr8a.pfb " TeXBase1Encoding ReEncodeFont "
aubro8r UniversCE-BlackOblique <[8r.enc <aubro8a.pfb " TeXBase1Encoding ReEncodeFont "
aunb8r UniversCE-Bold <[8r.enc <aunb8a.pfb " TeXBase1Encoding ReEncodeFont "
aunbo8r UniversCE-BoldOblique <[8r.enc <aunbo8a.pfb " TeXBase1Encoding ReEncodeFont "
aunl8r UniversCE-Light <[8r.enc <aunl8a.pfb " TeXBase1Encoding ReEncodeFont "
aunlo8r UniversCE-LightOblique <[8r.enc <aunlo8a.pfb " TeXBase1Encoding ReEncodeFont "
aunr8r UniversCE-Medium <[8r.enc <aunr8a.pfb " TeXBase1Encoding ReEncodeFont "
aunro8r UniversCE-Oblique <[8r.enc <aunro8a.pfb " TeXBase1Encoding ReEncodeFont "
dinb8r DIN-Bold <[8r.enc <dinb8a.pfb " TeXBase1Encoding ReEncodeFont "
dinbo8r DIN-Bold <[8r.enc <dinb8a.pfb " TeXBase1Encoding ReEncodeFont 0.167 SlantFont "

so far I didn't know that this is in tudscr.map, now. @mrpiggi  could you comment on this?

some further remarks:
> \def\bbl@main@language{english}

You should use the high level Babel if possible e.g. the option`main=english`.

> \RequirePackage[english,ngerman]{babel}
\iflnienglish\selectlanguage{english}\def\bbl@main@language{english}\fi
\DeclareFixedFont{\univLightIX}{T1}{aun}{l}{n}{9}
\DeclareFixedFont{\univBoldIX}{T1}{aun}{b}{n}{9}
\DeclareFixedFont{\univLightXI}{T1}{aun}{l}{n}{11}
\DeclareFixedFont{\univLightObliqueXI}{T1}{aun}{l}{sl}{11}
\DeclareFixedFont{\univBoldXI}{T1}{aun}{b}{n}{11}
\DeclareFixedFont{\univLightVII}{T1}{aun}{l}{n}{7}
\DeclareFixedFont{\univLightObliqueVII}{T1}{aun}{l}{sl}{7}

Why not use tudscrfonts.sty instead? Mainaining fonts involves much more than just setting the main font. It can be used also in non-koma-script classes. I'm using it in the beamer style.

> \pdfmapfile{=tud.map}

When you have enabled the font map with updmap you don't need this line. Furthermore this line disables all enabled font maps. Are you sure that you don't want `\pdfmapfile{+tudscr.map}`, instead?

**Comment by nise** [comment]
Thank your for your advises. I will check them later. 

I am going to publish my class on github as soon as my dissertation project will be published. But as I said, I focused on the visible result, rather then beauty of code.  OpenSans as well as any newer style guide instructions are not relevant for me since I left TUD. 
However, there might be one thing that could be interesting for the community. I found a way to generate PDF/A which is required for long-term archiving at Qucosa.

**Comment by mrpiggi** [comment]
@keinstein The file `tudscr.map` looks like this:
```
lunr8r UniversCE-Medium <[8r.enc <lunr8a.pfb " TeXBase1Encoding ReEncodeFont "
lunro8r UniversCE-Oblique <[8r.enc <lunro8a.pfb " TeXBase1Encoding ReEncodeFont "
lunb8r UniversCE-Bold <[8r.enc <lunb8a.pfb " TeXBase1Encoding ReEncodeFont "
lunbo8r UniversCE-BoldOblique <[8r.enc <lunbo8a.pfb " TeXBase1Encoding ReEncodeFont "
lunc8r UniversCE-Black <[8r.enc <lunc8a.pfb " TeXBase1Encoding ReEncodeFont "
lunco8r UniversCE-BlackOblique <[8r.enc <lunco8a.pfb " TeXBase1Encoding ReEncodeFont "
lunl8r UniversCE-Light <[8r.enc <lunl8a.pfb " TeXBase1Encoding ReEncodeFont "
lunlo8r UniversCE-LightOblique <[8r.enc <lunlo8a.pfb " TeXBase1Encoding ReEncodeFont "
0m6b8r DIN-Bold <[8r.enc <0m6b8a.pfb " TeXBase1Encoding ReEncodeFont "
0m6bo8r DIN-Bold <[8r.enc <0m6b8a.pfb " TeXBase1Encoding ReEncodeFont 0.167 SlantFont "
```
And as suggested, package `tudscrfonts` should provide everything needed.

**Comment by keinstein** [comment]
Ok. Thanks for clarifying. So the code that @nise posted is either the contents of `univers.map` (old installation script) or of `tud.map` (mrpiggi's installation script).  I don't have any /var/lib/texmf/font/mp/pdflatex/updmap on my Debian system. So I can't directly provide any further information. But it looks as if the font map is globally installed, at least for something. `mp` might be connected to MetaPost.
